### ISSUE TITLE
git origin of this git repo is unknown

### ISSUE THREAD

**Issue by vermaete** [alliedvision/linux_imx6_4.1.15_nitrogen6max#1]
Hi,

I'm looking for the origin of this git repo.  I do assume it's or the 'linux-imx' of Freescale [1] or the 'linux-imx6' of Boundary Devices [2].
It would make it much easier to extract the changes you have made to create this driver if you could share the git repo you haved forked and the git hash where you have start working on.

Br,

[1]: http://git.freescale.com/git/cgit.cgi/imx/linux-imx.git
[2]: https://github.com/boundarydevices/linux-imx6

**Comment by fklostermann-avt** [comment]
Hi,

the git origin is documented in the ReleaseNotes.txt file:
https://github.com/alliedvision/linux_imx6_4.1.15_nitrogen6max/blob/master/ReleaseNotes.txt

repo: https://github.com/boundarydevices/linux-imx6/tree/boundary-imx_4.1.15_2.0.0_ga
commit: 719fb24c9923e424d25d1828cdd0c86f11ccb147

Best regards
